---

- name: Install Varnish
  package:
    name: varnish
    state: present

- name: Start varnish services on boot
  service:
    name: "{{ item }}"
    enabled: yes
  with_items: "{{ varnish_services }}"

- name: Copy generic varnish VCL
  copy:
    src: generic_vcl
    dest: /etc/varnish/default.vcl
    owner: root
    group: root
    mode: 0644
  notify: Restart varnish services