---

- name: Install Varnish
  yum:
    name: varnish
    state: present
    disable_excludes: all

- name: Start varnish services on boot
  service:
    name: "{{ item }}"
    enabled: yes
  with_items: "{{ varnish_services }}"