---

- name: Start varnish services
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ varnish_services }}"

- name: Stop varnish services
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ varnish_services }}"

- name: Restart varnish services
  service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ varnish_services }}"

- name: Reload varnish services
  service:
    name: "{{ item }}"
    state: reloaded
  with_items: "{{ varnish_services }}"